<?php

namespace App\Support;

use App\Models\Boost;
use App\Models\Message;
use Closure;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Cache;

final class MessageFragments
{
    public const VERSION = 'presentation-v4';

    public function render(iterable $messages): string
    {
        $messages = new EloquentCollection(Collection::make($messages)->values()->all());
        $messages->loadMissing('creator');
        $keys = $messages->map($this->messageKey(...))->all();
        $cached = Cache::many($keys);
        $missing = $messages->filter(fn (Message $message, int $i) => ! is_array($cached[$keys[$i]]));
        if ($missing->isNotEmpty()) {
            $missing->loadMissing(['creator', 'richText', 'attachment.blob.variantRecords', 'boosts.booster', 'room']);
            foreach ($missing as $i => $message) {
                $parts = $this->parts(fn () => view('messages.message', ['message' => $message])->render());
                Cache::put($keys[$i], $parts, now()->addDays(1));
                $cached[$keys[$i]] = $parts;
            }
        }

        return implode('', array_map(fn (string $key) => implode(e(csrf_token()), $cached[$key]), $keys));
    }

    public function boostHtml(Boost $boost): string
    {
        $boost->loadMissing('booster');
        $key = $this->boostKey($boost);
        $parts = Cache::get($key);
        if (! is_array($parts)) {
            $parts = $this->parts(fn () => view('boosts.boost-body', ['boost' => $boost])->render());
            Cache::put($key, $parts, now()->addDays(1));
        }

        return implode(e(csrf_token()), $parts);
    }

    public function messageKey(Message $message): string
    {
        return implode(':', ['message', self::VERSION, url('/'), $message->id,
            $message->getRawOriginal('updated_at'), $message->creator?->getRawOriginal('updated_at')]);
    }

    public function boostKey(Boost $boost): string
    {
        return implode(':', ['boost', self::VERSION, url('/'), $boost->id,
            $boost->getRawOriginal('updated_at'), $boost->booster?->getRawOriginal('updated_at')]);
    }

    // Split only tokens generated by the template. Message text may contain a real token.
    private function parts(Closure $render): array
    {
        $session = app('session.store');
        $original = $session->get('_token');
        $placeholder = 'csrf-'.bin2hex(random_bytes(16));
        $session->put('_token', $placeholder);
        try {
            return explode($placeholder, $render());
        } finally {
            $original === null ? $session->forget('_token') : $session->put('_token', $original);
        }
    }
}
