<?php

namespace App\Support;

use App\Models\Boost;
use App\Models\Message;
use Closure;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Illuminate\Support\Collection;

final class MessageFragments
{
    public const VERSION = 'presentation-v4';

    public function render(iterable $messages): string
    {
        $messages = new EloquentCollection(Collection::make($messages)->values()->all());
        $messages->loadMissing(['creator', 'room', 'boosts.booster']);
        $keys = $messages->map($this->messageKey(...))->all();
        $epoch = $this->epoch();
        $cache = app(ResponseCache::class);
        $cached = $epoch === null ? array_fill_keys($keys, null) : $cache->many($keys, $epoch);
        $missing = $messages->filter(fn (Message $message, int $i) => ! is_array($cached[$keys[$i]]));
        if ($missing->isNotEmpty()) {
            $missing->loadMissing(['creator', 'richText', 'attachment.blob.variantRecords', 'boosts.booster', 'room']);
            foreach ($missing as $i => $message) {
                $parts = $this->parts(fn () => view('messages.message', ['message' => $message])->render());
                if ($epoch !== null) {
                    $cache->put($keys[$i], $epoch, $parts);
                }
                $cached[$keys[$i]] = $parts;
            }
        }

        return implode('', array_map(fn (string $key) => implode(e(csrf_token()), $cached[$key]), $keys));
    }

    public function boostHtml(Boost $boost): string
    {
        $boost->loadMissing('booster');
        $key = $this->boostKey($boost);
        $epoch = $this->epoch();
        $cache = app(ResponseCache::class);
        $parts = $epoch === null ? null : $cache->get($key, $epoch);
        if (! is_array($parts)) {
            $parts = $this->parts(fn () => view('boosts.boost-body', ['boost' => $boost])->render());
            if ($epoch !== null) {
                $cache->put($key, $epoch, $parts);
            }
        }

        return implode(e(csrf_token()), $parts);
    }

    public function messageKey(Message $message): string
    {
        return 'message:'.hash('sha256', json_encode([
            self::VERSION, url('/'), $message->id,
            $message->getRawOriginal('updated_at'), $message->creator?->getRawOriginal('updated_at'),
            $message->room?->displayName(),
            $message->boosts->map($this->boostKey(...))->all(),
        ], JSON_THROW_ON_ERROR));
    }

    public function boostKey(Boost $boost): string
    {
        return implode(':', ['boost', self::VERSION, url('/'), $boost->id,
            $boost->getRawOriginal('updated_at'), $boost->booster?->getRawOriginal('updated_at')]);
    }

    private function epoch(): ?int
    {
        // Detached models have no safe snapshot; page capture already renders fresh.
        if (request()->attributes->get('campfire.capture_response', false)) {
            return null;
        }
        $epoch = request()->attributes->get('campfire.response_epoch');

        return is_int($epoch) ? $epoch : null;
    }

    // Split only tokens generated by the template. Message text may contain a real token.
    private function parts(Closure $render): array
    {
        $session = app('session.store');
        $original = $session->get('_token');
        $placeholder = 'csrf-'.bin2hex(random_bytes(16));
        $session->put('_token', $placeholder);
        try {
            return explode($placeholder, $render());
        } finally {
            $original === null ? $session->forget('_token') : $session->put('_token', $original);
        }
    }
}
